# Generated by Django 4.1.6 on 2023-03-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_issue_alter_status_options_alter_type_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True, verbose_name='Дата и время удаления'),
        ),
        migrations.AddField(
            model_name='issue',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='удалено'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Описание'),
        ),
    ]
